import { getTableColumns, getTableName } from "drizzle-orm";
import { getTableConfig } from "drizzle-orm/pg-core";
import { describe, expect, it } from "vitest";
import * as schema from "./index.js";

const expectedColumns = {
  access_decision_audit: [
    "id",
    "account_id",
    "actor_type",
    "actor_id",
    "correlation_id",
    "command_id",
    "check_kind",
    "allowed",
    "reason_code",
    "source_grant_ids",
    "snapshot_version",
    "snapshot_hash",
    "occurred_at",
  ],
  account_hold_sources: [
    "id",
    "account_id",
    "source_kind",
    "source_id",
    "target_source_registry_id",
    "created_at",
  ],
  account_holds: [
    "id",
    "account_id",
    "source_registry_id",
    "kind",
    "created_at",
    "released_at",
  ],
  accounts: [
    "id",
    "name",
    "status",
    "owner_established_at",
    "created_at",
    "updated_at",
  ],
  administrative_grant_restorations: [
    "new_source_registry_id",
    "account_id",
    "terminal_grant_id",
    "created_at",
  ],
  audit_events: [
    "id",
    "account_id",
    "actor_type",
    "actor_id",
    "action",
    "target_type",
    "target_id",
    "correlation_id",
    "payload",
    "occurred_at",
  ],
  business_os_setup_receipts: [
    "source_registry_id",
    "account_id",
    "reconciliation_id",
    "status",
    "created_at",
    "updated_at",
  ],
  business_os_subscription_cancellations: [
    "source_registry_id",
    "account_id",
    "paid_through_at",
    "created_at",
  ],
  club_subscription_cancellations: [
    "source_registry_id",
    "account_id",
    "paid_through_at",
    "created_at",
  ],
  commerce_fulfillment_receipts: [
    "source_registry_id",
    "account_id",
    "reconciliation_id",
    "status",
    "starts_at",
    "ends_at",
    "created_at",
    "updated_at",
  ],
  commerce_reconciliations: [
    "id",
    "account_id",
    "command_kind",
    "source_kind",
    "source_id",
    "request_fingerprint",
    "reason_code",
    "incident_kind",
    "target_source_registry_id",
    "expected_paid_through_at",
    "status",
    "review_due_at",
    "claimed_by_staff_id",
    "claimed_at",
    "resolved_at",
    "resolution_code",
    "created_at",
    "updated_at",
  ],
  entitlement_commands: [
    "command_id",
    "account_id",
    "command_kind",
    "actor_type",
    "actor_id",
    "first_correlation_id",
    "input_hash",
    "outcome",
    "result",
    "occurred_at",
    "completed_at",
  ],
  entitlement_grants: [
    "id",
    "account_id",
    "source_registry_id",
    "source_kind",
    "source_id",
    "offer_code",
    "capability",
    "status",
    "starts_at",
    "ends_at",
    "provenance",
    "created_at",
    "updated_at",
  ],
  entitlement_sources: [
    "id",
    "account_id",
    "source_kind",
    "source_id",
    "offer_code",
    "academy_source_registry_id",
    "provenance",
    "created_at",
  ],
  event_handler_receipts: [
    "handler_name",
    "event_id",
    "job_id",
    "account_id",
    "status",
    "worker_id",
    "attempt",
    "claim_generation",
    "claim_token",
    "lease_expires_at",
    "started_at",
    "completed_at",
    "updated_at",
  ],
  job_attempts: [
    "job_id",
    "account_id",
    "attempt",
    "claim_generation",
    "claim_token",
    "worker_id",
    "started_at",
    "lease_expires_at",
    "finished_at",
    "outcome",
    "error_code",
    "error_message",
  ],
  jobs: [
    "id",
    "account_id",
    "source_actor_type",
    "source_actor_id",
    "correlation_id",
    "queue",
    "type",
    "idempotency_key",
    "payload",
    "status",
    "priority",
    "attempts",
    "max_attempts",
    "run_at",
    "claimed_at",
    "worker_id",
    "lease_expires_at",
    "claim_token",
    "claim_generation",
    "completed_at",
    "last_error_code",
    "last_error_message",
    "created_at",
    "updated_at",
  ],
  member_identities: [
    "id",
    "account_id",
    "provider",
    "provider_user_id",
    "email",
    "created_at",
    "updated_at",
  ],
  memberships: [
    "id",
    "account_id",
    "member_identity_id",
    "role",
    "status",
    "created_at",
    "updated_at",
  ],
  outbox_events: [
    "id",
    "event_id",
    "account_id",
    "actor_type",
    "actor_id",
    "correlation_id",
    "type",
    "aggregate_id",
    "occurred_at",
    "payload",
    "schema_version",
    "status",
    "attempts",
    "max_attempts",
    "available_at",
    "claimed_at",
    "worker_id",
    "lease_expires_at",
    "claim_token",
    "claim_generation",
    "published_at",
    "dead_lettered_at",
    "last_error_code",
    "last_error_message",
    "created_at",
  ],
  provider_event_receipts: [
    "id",
    "provider",
    "provider_event_id",
    "status",
    "payload",
    "received_at",
    "processed_at",
    "last_error_code",
  ],
  seat_invitation_token_generations: [
    "id",
    "account_id",
    "invitation_id",
    "generation",
    "token_hash",
    "expires_at",
    "consumed_at",
    "superseded_at",
    "created_at",
  ],
  seat_invitations: [
    "id",
    "account_id",
    "normalized_email",
    "expires_at",
    "created_at",
  ],
  seat_reservations: [
    "id",
    "account_id",
    "slot",
    "source_registry_id",
    "state",
    "membership_id",
    "invitation_id",
    "expires_at",
    "created_at",
    "updated_at",
  ],
  staff_identities: [
    "id",
    "provider",
    "provider_user_id",
    "email",
    "display_name",
    "role",
    "status",
    "permissions",
    "created_at",
    "updated_at",
  ],
  staff_login_attempts: [
    "state_hash",
    "browser_nonce_hash",
    "verifier_ciphertext",
    "verifier_iv",
    "verifier_tag",
    "key_version",
    "prior_session_hash",
    "return_to",
    "expires_at",
    "consumed_at",
    "created_at",
  ],
  staff_sessions: [
    "session_hash",
    "previous_session_hash",
    "staff_identity_id",
    "workos_user_id",
    "workos_session_id",
    "organization_id",
    "provider_roles",
    "provider_permissions",
    "token_ciphertext",
    "token_iv",
    "token_tag",
    "key_version",
    "access_token_expires_at",
    "hard_expires_at",
    "authenticated_at",
    "refresh_version",
    "refresh_lease_id",
    "refresh_lease_expires_at",
    "revoked_at",
    "created_at",
    "updated_at",
  ],
} as const;

describe("foundation Drizzle schema", () => {
  it("declares the canonical account-name database check", () => {
    expect(getTableConfig(schema.accounts).checks.map((check) => check.name))
      .toContain("accounts_name_canonical_check");
  });

  it("declares the foundation and authentication table contracts", () => {
    const actual = Object.values(schema)
      .map((table) => [
        getTableName(table),
        Object.values(getTableColumns(table)).map((column) => column.name),
      ] as const)
      .sort(([left], [right]) => left.localeCompare(right));
    const foundationAndAuthentication = actual.filter(([tableName]) => (
      Object.hasOwn(expectedColumns, tableName)
    ));

    expect(actual).toHaveLength(71);
    expect(foundationAndAuthentication).toEqual(Object.entries(expectedColumns));
  });
});
