import { AlertCircle, Check, Clock3, ExternalLink, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { requireAdminAccess } from "@/lib/auth/staff-access";

const launchChecks = ["Test lead capture", "Qualification routing", "Booking path", "Email + SMS messages", "Client onboarding", "AI escalation", "Dashboard activity"];

export default async function AdminProvisioningPage() {
  await requireAdminAccess();
  return <div className="admin-page"><section className="admin-page-head"><div><span className="micro-label">Business OS operations</span><h1>Provisioning queue</h1><p>Configure, verify, and activate customer systems against the seven-check launch standard.</p></div><Button size="small" variant="secondary">Open HighLevel <ExternalLink size={14} /></Button></section><section className="provisioning-queue"><aside><div><span className="micro-label">In progress</span><strong>4 accounts</strong></div>{[["Northstar Advisory","Due Aug 18","blocked"],["Ortega Studio","Due Aug 19","healthy"],["Clearpath Legal Ops","Due Aug 20","healthy"],["Brooks & Field","Paused","paused"]].map(([name,due,status], index) => <button className={index === 0 ? "active" : ""} key={name} type="button"><span className={`queue-state ${status}`} /> <div><strong>{name}</strong><small>{due}</small></div><i className={`status-pill ${status}`}>{status}</i></button>)}</aside><section className="provisioning-detail"><header><div><span className="micro-label">Customer setup</span><h2>Northstar Advisory</h2><p>Started Aug 11 · Target Aug 18 · Owner: Talia Moore</p></div><span className="status-pill blocked">Blocked</span></header><div className="provisioning-alert"><AlertCircle size={16} /><div><strong>Waiting on messaging registration</strong><p>Customer identity verification is in progress. The SLA clock is paused while third-party review is pending.</p></div></div><div className="activation-list"><div><span className="micro-label">Activation standard</span><strong>4 of 7 checks passed</strong></div>{launchChecks.map((check, index) => <label key={check}><span className={index < 4 ? "done" : ""}>{index < 4 ? <Check size={13} /> : index + 1}</span><div><strong>{check}</strong><small>{index < 4 ? "Verified Aug 11 by Talia Moore" : "Required before activation"}</small></div>{index < 4 ? <ShieldCheck size={14} /> : <Clock3 size={14} />}</label>)}</div><footer><span>Activation is disabled until every check passes.</span><Button disabled size="small">Activate Business OS</Button></footer></section><aside className="provisioning-notes"><span className="micro-label">Internal notes</span><article><strong>Talia Moore</strong><time>Today, 2:10 PM</time><p>Lead routing and booking passed. Waiting on the A2P registration before testing outbound SMS.</p></article><label>Add an internal note<textarea placeholder="Visible only to admins and operators" /></label><Button size="small" variant="secondary">Save note</Button></aside></section></div>;
}
